# -*- coding: UTF-8 -*-
from core.test import BaseTestCase
from core.utils import urlify, Transliterator


TEST_PATTERNS = [
    (u'http://www.e-shtab.ru with a string',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a> with a string'),
    (u'http://www.e-shtab.ru, with a string',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>, with a string'),
    (u'http://www.e-shtab.ru! with a string',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>! with a string'),
    (u'http://www.e-shtab.ru',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>'),
    (u'http://www.e-shtab.ru,',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>,'),
    (u'http://www.e-shtab.ru!',
     u'<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>!'),
    (u'"http://www.e-shtab.ru"',
     u'&quot;<a href="http://www.e-shtab.ru">http://www.e-shtab.ru</a>&quot;'),
    (u'http://www.e-shtab.ru/ with a string',
     u'<a href="http://www.e-shtab.ru/">http://www.e-shtab.ru/</a> with a string'),
    (u'http://www.e-shtab.ru/',
     u'<a href="http://www.e-shtab.ru/">http://www.e-shtab.ru/</a>'),
    (u'www.e-shtab.ru with a string',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a> with a string'),
    (u'www.e-shtab.ru, with a string',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>, with a string'),
    (u'www.e-shtab.ru! with a string',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>! with a string'),
    (u'www.e-shtab.ru',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>'),
    (u'www.e-shtab.ru,',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>,'),
    (u'www.e-shtab.ru!',
     u'<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>!'),
    (u'"www.e-shtab.ru"',
     u'&quot;<a href="http://www.e-shtab.ru">www.e-shtab.ru</a>&quot;'),
    (u'www.e-shtab.ru/ with a string',
     u'<a href="http://www.e-shtab.ru/">www.e-shtab.ru/</a> with a string'),
    (u'www.e-shtab.ru/',
     u'<a href="http://www.e-shtab.ru/">www.e-shtab.ru/</a>'),
    (u'http://www.e-shtab.ru/user/1/ тут наш босс',
     u'<a href="http://www.e-shtab.ru/user/1/">http://www.e-shtab.ru/user/1/</a> тут наш босс'),
    (u'www.e-shtab.ru/user/1/ тут наш босс',
     u'<a href="http://www.e-shtab.ru/user/1/">www.e-shtab.ru/user/1/</a> тут наш босс'),
    (u'www.domain.com/file.html.',
     u'<a href="http://www.domain.com/file.html">www.domain.com/file.html</a>.'),
    (u'http://domain.com/file.html.',
     u'<a href="http://domain.com/file.html">http://domain.com/file.html</a>.'),
#*****
# WE DONT REALIZE THIS YET, because python don't support recursions regexp
#*****
#    (u'http://ru.wikipedia.org/1_(число) и текст',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a> и текст'),
#    (u'http://ru.wikipedia.org/1_(число), и текст',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>, и текст'),
#    (u'(http://ru.wikipedia.org/1_(число)) и текст',
#     u'(<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>) и текст'),
#    (u'http://ru.wikipedia.org/1_(число))) и текст',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>)) и текст'),
#    (u'http://ru.wikipedia.org/1(_(число)) и текст',
#     u'<a href="http://ru.wikipedia.org/1(_(число))">http://ru.wikipedia.org/1(_(число))</a> и текст'),
#    (u'http://ru.wikipedia.org/1(_(чи)сло)) и текст',
#     u'<a href="http://ru.wikipedia.org/1(_(чи)сло)">http://ru.wikipedia.org/1(_(чи)сло)</a>) и текст'),
#    (u'http://ru.wikipedia.org/1(_(чи)сло))))) и текст',
#     u'<a href="http://ru.wikipedia.org/1(_(чи)сло)">http://ru.wikipedia.org/1(_(чи)сло)</a>)))) и текст'),
#    (u'http://ru.wikipedia.org/1_(число)',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>'),
#    (u'http://ru.wikipedia.org/1_(число)',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>'),
#    (u'(http://ru.wikipedia.org/1_(число))',
#     u'(<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>)'),
#    (u'http://ru.wikipedia.org/1_(число)))',
#     u'<a href="http://ru.wikipedia.org/1_(число)">http://ru.wikipedia.org/1_(число)</a>))'),
#    (u'http://ru.wikipedia.org/1(_(число))',
#     u'<a href="http://ru.wikipedia.org/1(_(число))">http://ru.wikipedia.org/1(_(число))</a>'),
#    (u'http://ru.wikipedia.org/1(_(чи)сло))',
#     u'<a href="http://ru.wikipedia.org/1(_(чи)сло)">http://ru.wikipedia.org/1(_(чи)сло)</a>)'),
#    (u'http://ru.wikipedia.org/1(_(чи)сло))))',
#     u'<a href="http://ru.wikipedia.org/1(_(чи)сло)">http://ru.wikipedia.org/1(_(чи)сло)</a>)))'),
#    (u'www.jopapedia.org/1_(число) и текст',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a> и текст'),
#    (u'www.jopapedia.org/1_(число и текст',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>, и текст'),
#    (u'(www.jopapedia.org/1_(число)) и текст',
#     u'(<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>) и текст'),
#    (u'www.jopapedia.org/1_(число))) и текст',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>)) и текст'),
#    (u'www.jopapedia.org/1(_(число)) и текст',
#     u'<a href="http://www.jopapedia.org/1(_(число))">www.jopapedia.org/1(_(число))</a> и текст'),
#    (u'www.jopapedia.org/1(_(чи)сло)) и текст',
#     u'<a href="http://www.jopapedia.org/1(_(чи)сло)">www.jopapedia.org/1(_(чи)сло)</a>) и текст'),
#    (u'www.jopapedia.org/1(_(чи)сло))))) и текст',
#     u'<a href="http://www.jopapedia.org/1(_(чи)сло)">www.jopapedia.org/1(_(чи)сло)</a>)))) и текст'),
#    (u'www.jopapedia.org/1_(число)',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>'),
#    (u'www.jopapedia.org/1_(число)',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>'),
#    (u'(www.jopapedia.org/1_(число))',
#     u'(<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>)'),
#    (u'www.jopapedia.org/1_(число)))',
#     u'<a href="http://www.jopapedia.org/1_(число)">www.jopapedia.org/1_(число)</a>))'),
#    (u'www.jopapedia.org/1(_(число))',
#     u'<a href="http://www.jopapedia.org/1(_(число))">www.jopapedia.org/1(_(число))</a>'),
#    (u'www.jopapedia.org/1(_(чи)сло))',
#     u'<a href="http://www.jopapedia.org/1(_(чи)сло)">www.jopapedia.org/1(_(чи)сло)</a>)'),
#    (u'www.jopapedia.org/1(_(чи)сло))))',
#     u'<a href="http://www.jopapedia.org/1(_(чи)сло)">www.jopapedia.org/1(_(чи)сло)</a>)))'),
    (u'http://lleo.aha.ru/(na)/ а тут не ждут',
     u'<a href="http://lleo.aha.ru/(na)/">http://lleo.aha.ru/(na)/</a> а тут не ждут'),
    (u'www.lleo.aha.ru/(na)/ а тут не ждут',
     u'<a href="http://www.lleo.aha.ru/(na)/">www.lleo.aha.ru/(na)/</a> а тут не ждут'),
]


class UrlifyTestCase(BaseTestCase):
    def test(self):
        failed_patterns = []
        for pattern in TEST_PATTERNS:
            urlified = urlify(pattern[0])
            if urlified != pattern[1]:
                failed_patterns.append((pattern[0], pattern[1], urlified))
        self.assertFalse(failed_patterns,
            Transliterator().process(
                '\n\n'.join(['Pattern failed. \n patt: %s\n exp.: %s\n get : %s' % x for x in failed_patterns])))

